infotexture/dita-bootstrap

- .github/dita-ot/footer.xml
- .github/dita-ot/html.xml
- README.md
- includes/bs-footer-example.xml
- sample/index.dita
Describe footer  usage and add a footer to the online documentation
The icons in the footer will only display once #11 is processed.
> Add footer

- Customization/xsl/nav.xsl
- css/menubar-toc.css
- xsl/html5-bootstrap.xsl
Add spacer `<div>` and colorize background.
> Fix #33 - Menu bar ToC aligns with parent container.

- Customization/xsl/collapse.xsl
- Customization/xsl/utility-classes.xsl
- sample/collapse.dita
- sample/document.ditamap
- sample/offcanvas.dita
- xsl/html5-bootstrap-template.xsl
- xsl/html5-bootstrap.xsl
The Collapse component is very similar to the Offcanvas component. Just needs a simple XSL to handle visibility
- Updated XSL
- Updated Documentation
> Add collapse component support

- Customization/xsl/tables.xsl
- Customization/xsl/utility-classes.xsl
- README.md
- insertParameters.xml
- plugin.xml
- sample/index.dita
- sample/tables.dita
Additional `<table>` support options.
- Updated XSL
- Updated Documentation
- Additional parameters
> Additional table frame support

- css/custom.css
Regenerate `custom.css` using https://themestr.app/theme for Bootstrap 5
> Update Fresca theme to Bootstrap 5

- Customization/xsl/breadcrumb.xsl
- Customization/xsl/collapse.xsl
- Customization/xsl/nav.xsl
- Customization/xsl/pagination.xsl
- Customization/xsl/scrollspy.xsl
- Customization/xsl/tables.xsl
- Customization/xsl/tooltips.xsl
- Customization/xsl/topic.xsl
- package-lock.json
- plugin.xml
- sample/document.ditamap
- sample/figures.dita
- sample/rtl.dita
- sample/utilities.dita
- xsl/html5-bootstrap.xsl
> Prepare 5.3.2 release

- sample/index.dita
Amend Installation options to use Bootstrap tabs
> Switch to tabs

- sample/search-box.dita
Related https://github.com/infotexture/dita-bootstrap.lunr/pull/3
> Remove lunr.search parameter

- includes/bootstrap.hdf.rtl.xml
- includes/bootstrap.hdf.xml
- includes/bootstrap.icons.hdf.xml
Update to Bootstrap 5.3.0-alpha3 and Icons 1.10.5
> Bump Bootstrap versions of Scripts and Links

- .github/dita-ot/header.xml
- Customization/xsl/carousel.xsl
- Customization/xsl/nav.xsl
- Customization/xsl/tabs.xsl
- Customization/xsl/utility-classes.xsl
- css/menubar-toc.css
- css/none-toc.css
- css/side-toc.css
- includes/bootstrap.hdf.rtl.xml
- includes/bootstrap.hdf.xml
- includes/bs-navbar-default.hdr.xml
- includes/dark-mode-toggler.js
- plugin.xml
- xsl/html5-bootstrap.xsl
- update script and CSS
- remove `bg-light` for dark mode
- rewrite CSS for sidebar to align with Bootstrap 5.3 use of grid
- Add off-canvas mobile menu for alignment with Bootstrap 5.3.
> Update to 5.3

- Customization/xsl/scrollspy.xsl
- css/scrollspy-toc.css
Test with `default.language=ar` - e.g.
```
./dita -f html5-bootstrap -i ../document.ditamap  --nav-toc=collapsible --scrollspy-toc=list --default.language=ar
```
> Changes for RTL Scrollspy

- Customization/xsl/accordion.xsl
- sample/accordion.dita
Add `props="expand"` and `props="stay-open"`
- Update XSL
- Update docs
> Enhance accordion

- .github/dita-ot/header.xml
- .gitignore
- css/common-bootstrap.css
- includes/bs-navbar-default.hdr.xml
- sample/images.dita
Rename `bs-toggler-*` classes to allgn with Bootstrap `d-*` display classes.
Explain how to obtain different images for light and dark mode.
> Explain image toggler

- Customization/xsl/nav.xsl
- Customization/xsl/utility-classes.xsl
- README.md
- build_dita2html5-bootstrap_template.xml
- cfg/cosmo.properties
- cfg/lux.properties
- cfg/morph.properties
- cfg/pulse.properties
- cfg/yeti.properties
- css/collapsible-toc.css
- insertParameters.xml
- plugin.xml
- sample/index.dita
Tested with:
```console
./dita -i flowers/flowers.ditamap  \
--nav-toc=collapsible -f html5-bootstrap --bootstrap.theme=morph --default.language=en
```
```console
./dita -i flowers/flowers.ditamap \ 
--nav-toc=collapsible -f html5-bootstrap --bootstrap.theme=morph --default.language=ar
```
> Fix #104 - add defined button padding to collapsible sidebar

- Customization/xsl/carousel.xsl
- Customization/xsl/utility-classes.xsl
- README.md
- insertParameters.xml
- plugin.xml
- sample/alerts.dita
- sample/carousel.dita
- sample/collapse.dita
- sample/index.dita
- sample/typography.dita
- sample/utilities.dita
Add multiple images per strip with and without captions.
> Improve carousel.

- Customization/xsl/nav.xsl
- css/collapsible-toc.css
- includes/bootstrap.hdf.rtl.xml
- includes/bootstrap.hdf.xml
- includes/bootstrap.icons.hdf.xml
- includes/script-only.hdf.xml
- package-lock.json
- package.json
Update icons, update bootstrap
> Bootstrap 5.3.2

- sample/button-group.dita
- sample/document.ditamap
- sample/index.dita
- sample/sass.dita
- sample/scrollspy.dita
- sample/utilities.dita
@jason-fox The main changes here are in b1b573c. 
If that looks good to you, I'll sync the description to the [dita-bootstrap.sass `README.md`](https://github.com/infotexture/dita-bootstrap.sass/blob/develop/README.md).
The other commits are just small cleanup tasks that I noticed while testing the new topic.
> Add new topic on DITA Bootstrap Sass

- Customization/xsl/topic.xsl
Minor update to topic.xsl to fix issue #143 reported for imagemaps.
> Fix for imagemaps

- includes/bootstrap.icons.hdf.xml
> Bump icons version

- xsl/html5-bootstrap.xsl
> Rename BOOTSTRAP_DARK_MODE_INCLUDE parameter

- Customization/xsl/carousel.xsl
- Customization/xsl/topic.xsl
- Customization/xsl/utility-classes.xsl
- Prefer mode over named template
- Add gen-user-* stubs for extension.
- Expand otherprops regex to allow for `-`
- Breakout Carousel functions for readability.
> Extensibility fixes

- css/side-toc.css
> Fix #89 - Remove side ToC max-width

- Customization/xsl/nav.xsl
Update "children" parameter in collapsible-toc template. Issue #160
> Update nav.xsl to fix collapsible TOC 

- Customization/xsl/topic.xsl
- Customization/xsl/utility-classes.xsl
- sample/images.dita
1. Support HTML `<picture>`
2. Support Lazy loading
> Responsive images: support `<picture>` element & lazy loading

- sample/bootstrap-extension.dita
- sample/document.ditamap
Basic documentation to link to the Bootstrap Extension plugin.
> Add Bootstrap Extension documentation

- .github/dita-ot/header.xml
- includes/bootstrap.hdf.rtl.xml
- includes/bootstrap.hdf.xml
- includes/script-only.hdf.xml
- includes/theme.hdf.xml
- package-lock.json
- package.json
Update Bootstrap and Bootswatch - related #184 #182
> Update to Bootstrap 5.3.3

- .lefthook.yml
- package-lock.json
- package.json
Migrate from Husky + lint-staged to [Lefthook](https://evilmartians.com/chronicles/lefthook-knock-your-teams-code-back-into-shape) to simplify NPM dependencies & quiet Dependabot.
> Manage Git hooks with Lefthook
