infotexture/dita-bootstrap

css/custom.css

Bootstrap uses the class 'row' for part of its grid layout, but the HTML5 output uses the row class as well. 
This commit fixes that collision and makes tables display properly again.

Fixes #1. Make tables display properly again.

---

.github/dita-ot/header.xml
Customization/xsl/accordion.xsl
Customization/xsl/card.xsl
Customization/xsl/carousel.xsl
Customization/xsl/nav.xsl
Customization/xsl/offcanvas.xsl
Customization/xsl/tabs.xsl
README.md
includes/bootstrap.hdf.xml
includes/bootstrap.icons.hdf.xml
sample/accordion.dita
sample/alerts.dita
sample/badge.dita
sample/button-group.dita
sample/buttons.dita
sample/card.dita
sample/carousel.dita
sample/grid.dita
sample/icons.dita
sample/images.dita
sample/index.dita
sample/list-group.dita
sample/offcanvas.dita
sample/tables.dita
sample/tabs.dita
sample/utilities.dita
xsl/html5-bootstrap.xsl

Amend header files to use the latest releases
- Bootstrap 5.1.3
- Bootstrap Icons 1.7.2
Update attribution texts to follow [best practice](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution#This_is_a_good_attribution_for_material_from_which_you_created_a_derivative_work) for a derivative work.

Update dependencies: Bootstrap 5.1.3 & Bootstrap icons 1.7.2

---

Customization/xsl/topic.xsl
Customization/xsl/utility-classes.xsl
README.md
insertParameters.xml
plugin.xml
sample/document.ditamap
sample/figures.dita
sample/index.dita
sample/utilities.dita

Adds Bootstrap 5 [Figure](https://getbootstrap.com/docs/5.0/content/figures/) support
- Update XSL
- Update Documentation
- Add three parameter overrides -`bootstrap.css.figure` ,`bootstrap.css.figure.caption` , `bootstrap.css.figure.image`
Example of proper `<fig>` elements in use can be found [here](https://jason-fox.github.io/dita-ot-plugins/unit-test/usage.html)
Not just  `<fig>`, but all DITA elements which support the `@frame` display attribute are properly displayed using Bootstrap - this adds proper `@frame="sides"` support to `<codeblock>` and `<lines>`

Bootstrap Figure support

---

.github/dita-ot/footer.xml
.github/dita-ot/html.xml
Customization/xsl/popovers.xsl
Customization/xsl/tooltips.xsl
README.md
build_dita2html5-bootstrap.xml
insertParameters.xml
plugin.xml
sample/document.ditamap
sample/icons.dita
sample/index.dita
sample/popovers.dita
sample/tooltips.dita
xsl/html5-bootstrap-template.xsl
xsl/html5-bootstrap.xsl

Adds support for Bootstrap [Tooltip](https://getbootstrap.com/docs/5.0/components/tooltips/) and [Popover](https://getbootstrap.com/docs/5.0/components/popovers/) components
- Update XSL
- Update Documentation
- Add parameter override - `popovers.include`
Like Icons, Popovers are opt-in. The Documentation has been updated to clarify this.

Bootstrap Popover and Tooltip Support

---

Customization/xsl/topic.xsl
Customization/xsl/utility-classes.xsl
README.md
insertParameters.xml
plugin.xml
sample/document.ditamap
sample/index.dita
sample/typography.dita

Abbreviations, Definition List, Display Heading, Lead and Blockquote Support.
DITA equivalents of the Bootstrap elements defined  [here](https://getbootstrap.com/docs/5.1/content/typography/) - this is mainly just documentation since the layout is triggered off `outputclass`. Blockquote support relies on Figure support as defined in PR  #20  to  some extent, so this PR extends the other one an should be reviewed after the other one has been merged and that will reduce this review down to just two commits: 017546b eb95470

Typography Support

---

Customization/xsl/utility-classes.xsl
README.md
insertParameters.xml
plugin.xml
sample/index.dita

Given the following structure:
```xml
<topic>
<title>Styled as Bootstrap h1</title>
<body>
<section>
<title>Styled as Bootstrap h2*</title>
</section>
</body>
<topic>
<title>Styled as Bootstrap h2</title>
<body>
<section>
<title>Styled as Bootstrap h3*</title>
</section>
</body>
</topic>
<topic>
<title>Styled as Bootstrap h2</title>
<body>
<section>
<title>Styled as Bootstrap h3*</title>
</section>
</body>
</topic>
</topic>
```
The existing `bootstrap.css.header` param would style all the headers in the same fashion *regardless* of whether they are `<topic>` or `<section>` elements. Also the size of a `<section>` `<title>` would vary dependent upon the level of embedding. Spliting out `bootstrap.css.topic.title`  and `bootstrap.css.section.title` allows for  `<section>`  `<title>` …

Split CSS processing for topic titles and section titles

---

Customization/xsl/nav.xsl
README.md
insertParameters.xml
plugin.xml
sample/index.dita

```console
dita -f html5-bootstrap --nav-toc=nav-pill-full -i document.ditamap 
```
Setting css parameter to blank removes additional bootstrap classes from ancestors
```console
./dita -f html5-bootstrap --nav-toc=nav-pill-full \
--bootstrap.css.nav.parent='' -i document.ditamap
```
```console
./dita -f html5-bootstrap --nav-toc=nav-pill-full \
--bootstrap.css.nav.parent='bg-secondary text-muted' -i document.ditamap
```

Fix #32 - Make `active` class for active page ancestors configurable.

---

.github/dita-ot/html.xml
README.md
plugin.xml
sample/icons.dita
sample/index.dita

Implemented remaining suggestions from https://github.com/infotexture/dita-bootstrap/pull/40#issuecomment-1106069443 & https://github.com/infotexture/dita-bootstrap/pull/40#issuecomment-1106737205, tweaked README & bumped plug-in version.
Should be ready to tag for 5.3.1, just need to draft release summary.

Prepare 5.3.1 release

---

Customization/xsl/topic.xsl

Limit XSL override for `<fig>` elements so that Syntax Diagrams display correctly.

Fix Syntax Diagrams

---

Customization/xsl/nav.xsl
Customization/xsl/topic.xsl
README.md
build_dita2html5-bootstrap.xml
css/collapsible-toc.css
includes/bootstrap.hdf.rtl.xml
includes/bootstrap.hdf.xml
insertParameters.xml
plugin.xml
sample/document.ditamap
sample/index.dita
sample/rtl.dita

Bootstrap 5.2.0 brings full support for RTL languages like Arabic
- load alternate Bootstrap CSS
- Amend collapsible CSS
- Update Nav.xsl to encode images and links in a RTL friendly manner

RTL support

---

.github/dita-ot/html.xml
.github/workflows/ci.yml

Use https://github.com/jason-fox/fox.jason.open-graph to add OpenGraph meta data to build
Working example: https://jason-fox.github.io/dita-bootstrap/
See: https://opengraph.dev/panel?url=https%3A%2F%2Fjason-fox.github.io%2Fdita-bootstrap%2F

Add open-graph metadata

---

.github/workflows/ci.yml

@jason-fox I'd like to update the commit message that's used when [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) deploys the latest changes from the `develop` branch to GitHub Pages.
Based on the commits attributed to **GitHub Action** in your fork, I assume you've done something similar there.
Always hard to test CI without pushing spurious commits.
Does this look right?

Update commit message & author for CI deployments

---

Customization/xsl/utility-classes.xsl

Bootstrap splits rows into 12 sections.
- one term takes 3 columns, with 9 columns for the description (as before)
- two terms take 2 columns each, with 8 columns for the description
- three terms take 2 columns each, with 6 columns for the description
- four terms take 1 column each, with 8 columns for the description
- additional description lines take 12 columns.
Previously 2 or more terms would cause the columns  count to be greater than 12 causing misalignments.

Improve definition list handling

---

build_dita2html5-bootstrap_template.xml
plugin.xml

Simplify by removing unnecessary extension point
```console
./dita -f html5-bootstrap \
-i ../plugins/dita-bootstrap/sample/document.ditamap
```console
./dita -f html5-bootstrap \
-i ../plugins/dita-bootstrap/sample/document.ditamap \
--bootstrap.theme=simplex```
```
```console
./dita -f html5-bootstrap \
-i ../plugins/dita-bootstrap/sample/document.ditamap '
--bootstrap.sass=yes   ```
```
```console
./dita -f html5-bootstrap \
-i ../plugins/dita-bootstrap/sample/document.ditamap \
--args.copycss=yes \
--args.csspath=css \
--args.cssroot=${PWD}/../plugins/dita-bootstrap/css \
--args.css=custom.css
```

Remove extension point

---

.prettierignore
sample/document.ditamap
sample/offline.dita

Update the documentation to describe how to create an additional custom plugin which offers **offline mode** - this procedure is not recommended for a production environment since it avoids caching of files from the Internet and would be slower than normal online.
Custom plugin because adding it directly would also bloat the plugin codebase with unnecessary duplicates of the Bootstrap files.

Describe offline mode

---

css/menubar-toc.css
css/none-toc.css
css/scrollspy-toc.css
css/side-toc.css

Discovered whilst testing #102
Minor rejig of scroll margin values to support more use cases. It used to be the case that `scroll-margin` was only added if a scroll spy was present since that was when **jump to topic** was used, however this is not the only case. It is also possible to have a **jump to topic** when using   the `chunk="to-content"` attribute on a topic. This makes the **jump to topic**  present on the sidebar.
So the `scroll-margin` needs to shift to `sidebar-toc` from `scrollspy-toc`, and an additional override needs to be present if there is a menu bar as well.

Tweak Scroll Margin values

---

build_dita2html5-bootstrap_template.xml

Using `<makeurl>` does no harm, and could fix an Windows issue.

Potential fix #101 = use make URL to avoid windows slash issue.

---

Customization/xsl/utility-classes.xsl

` <xsl:next-match/>` means that it is possible to add new classes in addition to the bootstrap classes  to the  HTML output in further plugins.
e.g. to add a `line-numbers` CSS class add the following:
```xml
<xsl:template match="*[contains(@class, ' pr-d/codeblock ') and contains(@otherprops, 'line-numbers')]" mode="get-output-class">
<xsl:text> line-numbers</xsl:text>
<xsl:next-match/>
</xsl:template>
```

Allow for extensions of CSS classes by other plugins

---

Customization/xsl/accordion.xsl
Customization/xsl/utility-classes.xsl
sample/accordion.dita

Remove `otherprops` and use `outputclass`

Simplify Accordion markup

---

.github/dita-ot/footer.xml
.github/dita-ot/theme.css
Customization/xsl/topic.xsl
README.md
includes/bs-footer-example.xml
insertParameters.xml
plugin.xml
sample/index.dita

Autostyle the `<footer>` element using standard Bootstrap - e.g. `simplex`
- Update XSL with a sane default.
- Add `bootstrap.css.footer` paramter
- Update documentation
-  Update sample footer
- Remove custom CSS from GitHub Action

Add Bootstrap classes to Footer

---

Customization/xsl/nav.xsl
css/collapsible-toc.css
sample/document.ditamap
sample/icons.dita
sample/index.dita
sample/nav.dita

Add `  <othermeta name="spacer".../>` with or without additional content.
```xml
<topicref navtitle="Search Box" format="dita" type="topic" href="search-box.dita">
<topicmeta>
<othermeta name="icon" content="bi-search"/>
<othermeta name="spacer" content="Additional Plug-ins"/>
</topicmeta>
</topicref>
```
If `content=""` then a spacer is added with no content.

Add divider option

---

Customization/xsl/card.xsl
sample/card.dita

To ensure full compatibility with DITA 2.0, the reference to a `<sectiondiv>` should be switched to a `<div>`. I've left  `<sectiondiv>` processing in as well for backward compatibility to DITA 1.4.
>  Per discussion at TC May 18 2021, agreed to remove `<sectiondiv>` which is a subset of functionality now available with `<div>`.
_Originally posted by @robander in https://github.com/oasis-tcs/dita/issues/397#issuecomment-843271924_

Switch card headers from `<sectiondiv>` to `<div>`

---

Customization/xsl/nav.xsl
README.md
includes/hdr.navbar.default.xml
includes/hdr.navbar.example.xml
includes/hdr.topbar.example.xml
insertParameters.xml
plugin.xml
sample/index.dita
xsl/html5-bootstrap.xsl

The `bootstrap.css.container.size` parameter defines the size of the main layout div (`id=content`) and the menubar-TOC container. This allows more flexibility to adjust the site layout, and makes it possible to match the layout with a custom header if needed. 
Default value is `container-xxl`.

Add bootstrap.css.container.size parameter

---

.github/dita-ot/header.xml
includes/hdr.navbar.example.xml

**Cosmo** theme is currently missing from `header.xml` and therefore not in the sample theme selector on the website. Adding that one here.
The light navbar sample (`hdr.navbar.example.xml`) currently shows all icons simultaneously. Changing to `d-light`, etc... fixes this.

Add Cosmo theme to header.xml and fix light navbar icons

---

Customization/xsl/nav.xsl
css/collapsible-toc.css

Fix Focus outline for 5.3.3

---

Customization/xsl/utility-classes.xsl
README.md
sample/index.dita
sample/typography.dita

The parameter list `<parml>` element contains a list of terms and definitions that describes the parameters in an application programming interface. 
Because a lot of the bootstrap params are quite long, I've overridden the breakpoint and added proper wrapping for mobile where necessary.

Switch to parml

---

Customization/xsl/topic.xsl
xsl/html5-bootstrap.xsl

Fixes #190
When using bootstrap 5, flexbox can be used to achieve desired effect:
```xml
<body class="d-flex flex-column min-vh-100">
<header>HEADER</header>
<content>CONTENT</content>
<footer class="mt-auto"></footer>
</body>
```

Add `fixed-bottom` to footer

---

plugin.xml

@lakokkonen  - could you confirm that this change fixes your Oxygen issue?

Fix #213 - duplicate default HTML Parameters

---

Customization/xsl/topic.xsl

Explicitly insert the Unicode hex character code `&#xa;` for the Line Feed (LF) character instead of relying on the line break in the `<xsl:text>` element.
_(This approach is more resilient if the XSL source file is inadvertently re-formatted or re-indented.)_
As suggested by @stefan-jung in https://github.com/prettier/plugin-xml/issues/748#issuecomment-2009601555. 🙇

Use line feed character code in `$newline` variable

---

.github/dita-ot/header.xml
includes/bootstrap.hdf.rtl.xml
includes/bootstrap.hdf.xml
includes/script-only.hdf.xml
includes/theme.hdf.xml
package-lock.json
package.json
plugin.xml

Includes changes from 366de71:

Prepare 5.3.6 release

---

.github/dita-ot/header.xml
includes/bootstrap.hdf.rtl.xml
includes/bootstrap.hdf.xml
includes/bootstrap.icons.hdf.xml
includes/script-only.hdf.xml
includes/theme.hdf.xml
package-lock.json
package.json
plugin.xml
sample/alerts.dita
sample/images.dita
sample/index.dita
sample/nav.dita
sample/offline.dita
sample/search-box.dita
sample/tables.dita
sample/tooltips.dita

> Bootstrap v5.3.8 is out with a reversion for a dropdown focus bug, some CSS updates, 
> and several docs updates. The plan is for this to be the last patch release before v5.4.0 drops.
see [here](https://blog.getbootstrap.com/2025/08/25/bootstrap-5-3-8/)
- Bump Bootstrap to 5.3.8
- Bump Bootswatch to 5.3.7
- Bump Icons to 1.13.1
- Add `brite` Bootswatch theme
This will also close #263 and #256

Update Dependencies Again
